spring:
  data:
    mongodb:
      uri: ${MONGODB_AI_URI}
      database: ${MONGODB_AI_DATABASE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: ${OPENAI_API_BASE_URL}
  model: ${OPENAI_API_MODEL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME}
  queue:
    analysis-name: ${RABBITMQ_ANALYSIS_QUEUE_NAME}
    status-name: ${RABBITMQ_STATUS_QUEUE_NAME}
  routing:
    analysis-key: ${RABBITMQ_ANALYSIS_ROUTING_KEY}
    status-key: ${RABBITMQ_STATUS_ROUTING_KEY}

server:
  port: 8083
