spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8084/realms/jobkaki-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: job-service
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/api/users/*/jobs/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/job-analyses/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
