spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8084/realms/jobkaki-oauth2}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8084/realms/jobkaki-oauth2}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: job-service
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/api/users/*/jobs/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/job-analyses/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
