spring:
  application:
    name: ai-service

  config:
    import: optional:file:.env[.properties]

  mongodb:
    uri: ${MONGODB_AI_URI:mongodb://localhost:27017/fitness_ai}
    database: ${MONGODB_AI_DATABASE:fitness_ai}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    
openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: ${OPENAI_API_BASE_URL:https://api.openai.com/v1}
  model: ${OPENAI_API_MODEL:gpt-4o-mini}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME}
  queue:
    name: ${RABBITMQ_QUEUE_NAME}
  routing:
    key: ${RABBITMQ_ROUTING_KEY}

server:
  port: 8083