spring:
  data:
    mongodb:
      uri: ${MONGODB_JOB_URI}
      database: ${MONGODB_JOB_DATABASE}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME}
  queue:
    analysis-name: ${RABBITMQ_ANALYSIS_QUEUE_NAME}
    status-name: ${RABBITMQ_STATUS_QUEUE_NAME}
  routing:
    analysis-key: ${RABBITMQ_ANALYSIS_ROUTING_KEY}
    status-key: ${RABBITMQ_STATUS_ROUTING_KEY}

services:
  user:
    base-url: ${USER_SERVICE_BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

server:
  port: 8082
