
spring:
  application:
    name: user-service

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
server:
  port: 8081