
spring:
  application:
    name: user-service

  config:
    import: optional:file:./.env[.properties]

  data:
    mongodb:
      uri: ${MONGODB_USER_URI:mongodb://localhost:27017/jobkaki_users}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
server:
  port: 8081