spring:
  application.name: job-service
  config.import: optional:file:.env[.properties]
  data.mongodb.uri: ${MONGODB_JOB_URI:mongodb://localhost:27017/jobkaki_jobs}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME:jobkaki.job.exchange}
  queue:
    analysis-name: ${RABBITMQ_ANALYSIS_QUEUE_NAME:jobkaki.job.analysis}
    status-name: ${RABBITMQ_STATUS_QUEUE_NAME:jobkaki.job.status}
  routing:
    analysis-key: ${RABBITMQ_ANALYSIS_ROUTING_KEY:jobkaki.job.analyze}
    status-key: ${RABBITMQ_STATUS_ROUTING_KEY:jobkaki.job.status}
eureka.client.service-url.defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
server.port: 8082
